### ISSUE TITLE
Doesn't work with TMP Input Field

### ISSUE THREAD

**Issue by awesam85** [mitay-walle/Unity3d-TMPro-Text-AutoSize#1]
Hi

This is exactly what I've been looking for, but I cannot get it to work with TMP Input field, please help!

Thank you!

**Comment by awesam85** [comment]
Hi Mitay, when do you think you'll fix this? Thanks!

> Hi
> 
> This is exactly what I've been looking for, but I cannot get it to work with TMP Input field, please help!
> 
> Thank you!

Hey Mitay, when do you think this will be fixed? Thanks!

**Comment by mitay-walle** [comment]
> when do you think this will be fixed? Thanks!
@awesam85 
Hello, I've started work on it, at the end the week it will be fixed

**Comment by mitay-walle** [comment]
@awesam85 please, check new version with your configuration, what should you do, to make TMP_InputField work:

- add TMP_InputField.textComponent to TMPAutoSize.labels
- add TMP_InputField to TMPAutoSize.inputs
- optional | add TMP_InputField.placeholder to TMPAutoSize.labels

**Comment by mitay-walle** [comment]
Fixed as possible

**Comment by awesam85** [comment]
Thanks

> @awesam85 please, check new version with your configuration, what should you do, to make TMP_InputField work:
> 
> * add TMP_InputField.textComponent to TMPAutoSize.labels
> * add TMP_InputField to TMPAutoSize.inputs
> * optional | add TMP_InputField.placeholder to TMPAutoSize.labels

Thanks Dmitry!

Won’t be able to test until next week but I’ll let you know around next weekend how I get on 👍🏻

**Comment by awesam85** [comment]
Works Great!!
